### ISSUE TITLE
Set of quads is not a set

### ISSUE THREAD

**Issue by jeswr** [iherman/rdfjs-c14n#10]
The line in https://github.com/iherman/rdfjs-c14n/blob/588fdf33d3325c45e508cc90e810c231ceefce8a/testing/run/rdfn3.ts#L45  will not remove semantically equal quads as the `Set` constructor will only check if the quads are distinct Javascript objects.

To fix this I would recommend loading the quads into an rdfjs dataset (I reccomend the [n3.js](https://github.com/rdfjs/n3.js) implementation) and then iterating over the dataset which will result in semantically distinct quads.

**Comment by iherman** [comment]
@jeswr, thanks for the input (also for #9).

I have two questions: 
1. can you show me an example where this distinction matters? Possibly as a test case for RDFC? The reason I am asking this is that the [RDFC algorithm](https://www.w3.org/TR/rdf-canon/#canon-algorithm) ignores semantically equivalent terms like, for example, equivalent datatype entries, which means that usage of such terms ***does*** lead to a possibly different canonical form (after all, the algorithm does hashing over hashing over hashing...). Ie, it may well be that the usage of Sets ***is*** the right tool to use.

2. If the usage of rdfjs datasets is indeed the right tool: the core library also uses sets, see, https://github.com/iherman/rdfjs-c14n/blob/588fdf33d3325c45e508cc90e810c231ceefce8a/lib/common.ts#L31 and https://github.com/iherman/rdfjs-c14n/blob/588fdf33d3325c45e508cc90e810c231ceefce8a/lib/common.ts#L36 However, I have the feeling that this does not really matter once the `rdf.Quad` is used as part of the Set, to the only point where that counts is in the turtle->quads conversion. Is that correct? Or should Sets be replaced in the aforementioned lines, too? That would be a slightly more complicated surgery...


cc-ing the co-authors of the algorithm here, in case this becomes an issue for RDFC: @dlongley, @dlehn, @pchampin, @gkellogg

**Comment by jeswr** [comment]
Ah, sorry - sloppy use of language in my original comment -  I meant to say syntactic. That is, if you have 2 duplicates of exactly the same triple/quad in a document. I.e. if your document looks like:

```ttl
<a> <b> <c> .
<a> <b> <c> .
```

Then, most RDFJS parsers will return 2 quads that are distinct JavaScript objects; and so you will have duplicates of identical quads in your set because the set operation works at the level of JS objects, not the values those objects contain.

**Comment by jeswr** [comment]
> Or should Sets be replaced in the aforementioned lines, too?

I think it would be more RDFJS idomatic to be using the `DatasetCore` interface from `@rdfjs/types` here https://github.com/rdfjs/types/blob/ec006f7e646e5ed4bc257c8f51d10191e5cd1ee3/dataset.d.ts#L7-L48

cc @tpluscode who does most of the maintenance of those types

**Comment by iherman** [comment]
> > Or should Sets be replaced in the aforementioned lines, too?
> 
> I think it would be more RDFJS idomatic to be using the `DatasetCore` interface from `@rdfjs/types` here https://github.com/rdfjs/types/blob/ec006f7e646e5ed4bc257c8f51d10191e5cd1ee3/dataset.d.ts#L7-L48
> 
> cc @tpluscode who does most of the maintenance of those types

Well... at this moment, the core algorithmic part is done independently of any specific implementations of the various RDF-JS interfaces as much as possible. The only goal is to implement RDFC; the only n3 dependency I have is the turtle parser. I would prefer it this way, if someone wants to use the core canonicalization using a different environment

_Within_ the RDFC code using a Set for quads as one of the possible ways of storing quads seems to be perfectly fine. Others may want to algorithm using an array of quads, and that is again fine (and my code is prepared to it). Bringing in the Dataset into the code requires an implementation thereof, which is a dependency I would prefer not to have (with all my friendship to Ruben & co!). (I actually did have Datasets in the code for a while and it complicated things. That is why I removed it.)

The only question is whether the n3 turtle parser suffers the defficiencies that you describe in https://github.com/iherman/rdfjs-c14n/issues/10#issuecomment-1931630490. I will have to check that (unless you know the answer from the top of your head). If n3 returns only one quad, then I think no change is necessary...

**Comment by iherman** [comment]
N3 seems to return duplicate quads indeed (if Set is used). But I have the impression that this requires first a check with the WG on what the correct approach is. I have raised an issue there: https://github.com/w3c/rdf-canon/issues/191

**Comment by jeswr** [comment]
> I will have to check that (unless you know the answer from the top of your head). If n3 returns only one quad, then I think no change is necessary...

That parser will return duplicates - this is a design choice due to the streaming nature of the parser.

**Comment by tpluscode** [comment]
> at this moment, the core algorithmic part is done independently of any specific implementations of the various RDF-JS interfaces as much as possible

If I may jump in, I don't understand the premise of this statement. There is only one RDF/JS interface. That is its purpose of being the common denominator for various implementations. Seeing that the readme mentions RDF/JS, I would not shy away from using a `DatasetCore` **internally** if it is desired to deduplicate parsed triples. You might throw it away immediately and make it an implementation detail.

You could even go a little lighter with [`TermSet`](https://npm.im/@rdfjs/term-set). It is an RDF-aware implementation of JS `Set`

```ts
import { Quad } from '@rdfjs/types'
import TermSet from '@rdfjs/term-set'

# allow made up syntax to represent two equal quad object
const quad1: Quad = rdf`<a> <b> <c>`
const quad2: Quad = rdf`<a> <b> <c>` 

const set: Set<Quad> = new TermSet()

set.add(quad1).add(quad2)

# set.size === 1
```

On a related note, in the readme you write

```
An input RDF Dataset may be represented by:

* A Set of Quad instances; or
* An Array of Quad instances; or
 *A string representing an N-Quads document.
```

I would suggest implementing the interface using `Iterable<Quad>`. This will cover native sets and arrays, as well as `TermSet` and RDF/JS Datasets, without going into discussions on RDF semantics versus JS semantics.

**Comment by iherman** [comment]
> > at this moment, the core algorithmic part is done independently of any specific implementations of the various RDF-JS interfaces as much as possible
> 
> If I may jump in, I don't understand the premise of this statement.

My apologies, I misspoke. I meant any specific implementations of the RDF-JS interface as much as possible.

**Comment by iherman** [comment]
> I would suggest implementing the interface using `Iterable<Quad>`. This will cover native sets and arrays, as well as `TermSet` and RDF/JS Datasets, without going into discussions on RDF semantics versus JS semantics.

Sounds like a good idea; this requires some more work, but would probably simplify the code at the end. Will look into it.
